# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task6_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 144)
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setObjectName("formLayout")
        self.lbl_ligin = QtWidgets.QLabel(Dialog)
        self.lbl_ligin.setObjectName("lbl_ligin")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_ligin)
        self.line_login = QtWidgets.QLineEdit(Dialog)
        self.line_login.setObjectName("line_login")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_login)
        self.lbl_password = QtWidgets.QLabel(Dialog)
        self.lbl_password.setObjectName("lbl_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_password)
        self.line_password = QtWidgets.QLineEdit(Dialog)
        self.line_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_password.setObjectName("line_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.line_password)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.btn_register = QtWidgets.QPushButton(Dialog)
        self.btn_register.setObjectName("btn_register")
        self.horizontalLayout_2.addWidget(self.btn_register)
        self.btn_login = QtWidgets.QPushButton(Dialog)
        self.btn_login.setObjectName("btn_login")
        self.horizontalLayout_2.addWidget(self.btn_login)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_2)
        self.lbl_info = QtWidgets.QLabel(Dialog)
        self.lbl_info.setText("")
        self.lbl_info.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_info.setObjectName("lbl_info")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.lbl_info)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Войдите в систему"))
        self.lbl_ligin.setText(_translate("Dialog", "Логин"))
        self.lbl_password.setText(_translate("Dialog", "Пароль"))
        self.btn_cancel.setText(_translate("Dialog", "Отмена"))
        self.btn_register.setText(_translate("Dialog", "Регистрация"))
        self.btn_login.setText(_translate("Dialog", "Вход"))
