# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(567, 534)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_blue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_blue.setObjectName("btn_blue")
        self.gridLayout.addWidget(self.btn_blue, 1, 2, 1, 1)
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setObjectName("btn_left")
        self.gridLayout.addWidget(self.btn_left, 1, 3, 1, 1)
        self.btn_red = QtWidgets.QPushButton(self.centralwidget)
        self.btn_red.setObjectName("btn_red")
        self.gridLayout.addWidget(self.btn_red, 1, 0, 1, 1)
        self.btn_green = QtWidgets.QPushButton(self.centralwidget)
        self.btn_green.setObjectName("btn_green")
        self.gridLayout.addWidget(self.btn_green, 1, 1, 1, 1)
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setObjectName("btn_right")
        self.gridLayout.addWidget(self.btn_right, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Задание 1"))
        self.btn_blue.setText(_translate("MainWindow", "Синий"))
        self.btn_left.setText(_translate("MainWindow", "Повернуть влево"))
        self.btn_red.setText(_translate("MainWindow", "Красный"))
        self.btn_green.setText(_translate("MainWindow", "Зеленый"))
        self.btn_right.setText(_translate("MainWindow", "Повернуть вправо"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
