# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(592, 212)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.check1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check1.setObjectName("check1")
        self.verticalLayout_2.addWidget(self.check1)
        self.check2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check2.setObjectName("check2")
        self.verticalLayout_2.addWidget(self.check2)
        self.check3 = QtWidgets.QCheckBox(self.centralwidget)
        self.check3.setObjectName("check3")
        self.verticalLayout_2.addWidget(self.check3)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.line = QtWidgets.QLineEdit(self.centralwidget)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.text = QtWidgets.QTextEdit(self.centralwidget)
        self.text.setObjectName("text")
        self.gridLayout.addWidget(self.text, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 592, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.check1.setText(_translate("MainWindow", "CheckBox"))
        self.check2.setText(_translate("MainWindow", "CheckBox"))
        self.check3.setText(_translate("MainWindow", "CheckBox"))
