# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.text_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_2.setObjectName("text_2")
        self.gridLayout.addWidget(self.text_2, 3, 1, 1, 1)
        self.btn_obz = QtWidgets.QPushButton(self.centralwidget)
        self.btn_obz.setObjectName("btn_obz")
        self.gridLayout.addWidget(self.btn_obz, 0, 1, 1, 1)
        self.text_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_1.setObjectName("text_1")
        self.gridLayout.addWidget(self.text_1, 3, 0, 1, 1)
        self.ch = QtWidgets.QLabel(self.centralwidget)
        self.ch.setObjectName("ch")
        self.gridLayout.addWidget(self.ch, 2, 1, 1, 1)
        self.nech = QtWidgets.QLabel(self.centralwidget)
        self.nech.setObjectName("nech")
        self.gridLayout.addWidget(self.nech, 2, 0, 1, 1)
        self.line_file = QtWidgets.QLineEdit(self.centralwidget)
        self.line_file.setObjectName("line_file")
        self.gridLayout.addWidget(self.line_file, 0, 0, 1, 1)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Задание 2"))
        self.btn_obz.setText(_translate("MainWindow", "Обзор"))
        self.ch.setText(_translate("MainWindow", "Четные"))
        self.nech.setText(_translate("MainWindow", "Нечетные"))
        self.btn_start.setText(_translate("MainWindow", "Начать"))
