# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lab2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Lab2UI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(424, 311)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.task1 = QtWidgets.QPushButton(self.centralwidget)
        self.task1.setObjectName("task1")
        self.verticalLayout.addWidget(self.task1)
        self.task2 = QtWidgets.QPushButton(self.centralwidget)
        self.task2.setObjectName("task2")
        self.verticalLayout.addWidget(self.task2)
        self.task3 = QtWidgets.QPushButton(self.centralwidget)
        self.task3.setObjectName("task3")
        self.verticalLayout.addWidget(self.task3)
        self.task4 = QtWidgets.QPushButton(self.centralwidget)
        self.task4.setObjectName("task4")
        self.verticalLayout.addWidget(self.task4)
        self.task5 = QtWidgets.QPushButton(self.centralwidget)
        self.task5.setObjectName("task5")
        self.verticalLayout.addWidget(self.task5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 424, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная 2"))
        self.task1.setText(_translate("MainWindow", "Задание 1"))
        self.task2.setText(_translate("MainWindow", "Задание 2"))
        self.task3.setText(_translate("MainWindow", "Задание 3"))
        self.task4.setText(_translate("MainWindow", "Задание 4"))
        self.task5.setText(_translate("MainWindow", "Задание 5"))
