# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class NoteBookUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 0, 1, 1)
        self.phone_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_edit.setObjectName("phone_edit")
        self.gridLayout.addWidget(self.phone_edit, 1, 1, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout.addWidget(self.name_edit, 0, 1, 1, 1)
        self.btn_layout = QtWidgets.QHBoxLayout()
        self.btn_layout.setObjectName("btn_layout")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setEnabled(False)
        self.btn_add.setObjectName("btn_add")
        self.btn_layout.addWidget(self.btn_add)
        self.btn_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del.setEnabled(False)
        self.btn_del.setObjectName("btn_del")
        self.btn_layout.addWidget(self.btn_del)
        self.gridLayout.addLayout(self.btn_layout, 2, 0, 1, 2)
        self.phone = QtWidgets.QLabel(self.centralwidget)
        self.phone.setObjectName("phone")
        self.gridLayout.addWidget(self.phone, 1, 0, 1, 1)
        self.list = QtWidgets.QListWidget(self.centralwidget)
        self.list.setObjectName("list")
        self.gridLayout.addWidget(self.list, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Записная книжка"))
        self.name.setText(_translate("MainWindow", "Имя"))
        self.btn_add.setText(_translate("MainWindow", "Добавить"))
        self.btn_del.setText(_translate("MainWindow", "Удалить"))
        self.phone.setText(_translate("MainWindow", "Телефон"))
