# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plagiarism.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PlagiarismUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 589)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progress.setProperty("value", 0)
        self.progress.setTextVisible(True)
        self.progress.setObjectName("progress")
        self.gridLayout.addWidget(self.progress, 6, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.edit1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.edit1.setObjectName("edit1")
        self.gridLayout.addWidget(self.edit1, 0, 0, 1, 2)
        self.edit2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.edit2.setObjectName("edit2")
        self.gridLayout.addWidget(self.edit2, 0, 2, 1, 1)
        self.slider = QtWidgets.QSlider(self.centralwidget)
        self.slider.setMinimum(50)
        self.slider.setMaximum(149)
        self.slider.setProperty("value", 99)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.gridLayout.addWidget(self.slider, 5, 0, 1, 1)
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setEnabled(False)
        self.btn.setObjectName("btn")
        self.gridLayout.addWidget(self.btn, 4, 2, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 805, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Порог срабатывания"))
        self.btn.setText(_translate("MainWindow", "Проверить"))
