# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LoginUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(604, 240)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_login = QtWidgets.QLabel(self.centralwidget)
        self.lbl_login.setObjectName("lbl_login")
        self.gridLayout.addWidget(self.lbl_login, 0, 0, 1, 1)
        self.line_login = QtWidgets.QLineEdit(self.centralwidget)
        self.line_login.setObjectName("line_login")
        self.gridLayout.addWidget(self.line_login, 0, 1, 1, 1)
        self.lbl_password = QtWidgets.QLabel(self.centralwidget)
        self.lbl_password.setObjectName("lbl_password")
        self.gridLayout.addWidget(self.lbl_password, 1, 0, 1, 1)
        self.line_password = QtWidgets.QLineEdit(self.centralwidget)
        self.line_password.setObjectName("line_password")
        self.gridLayout.addWidget(self.line_password, 1, 1, 1, 1)
        self.lbl_phone = QtWidgets.QLabel(self.centralwidget)
        self.lbl_phone.setObjectName("lbl_phone")
        self.gridLayout.addWidget(self.lbl_phone, 2, 0, 1, 1)
        self.line_phone = QtWidgets.QLineEdit(self.centralwidget)
        self.line_phone.setObjectName("line_phone")
        self.gridLayout.addWidget(self.line_phone, 2, 1, 1, 1)
        self.lbl_info = QtWidgets.QLabel(self.centralwidget)
        self.lbl_info.setText("")
        self.lbl_info.setObjectName("lbl_info")
        self.gridLayout.addWidget(self.lbl_info, 4, 0, 1, 2)
        self.btn_log_in = QtWidgets.QPushButton(self.centralwidget)
        self.btn_log_in.setObjectName("btn_log_in")
        self.gridLayout.addWidget(self.btn_log_in, 3, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 604, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Зарегистрироваться"))
        self.lbl_login.setText(_translate("MainWindow", "Логин"))
        self.lbl_password.setText(_translate("MainWindow", "Пароль"))
        self.lbl_phone.setText(_translate("MainWindow", "Номер Телефона"))
        self.btn_log_in.setText(_translate("MainWindow", "Зарегистироваться"))
